version: '3'
services:
  mongo:
    image: mongo:3.6
  web:
    build: .
    ports:
        -name: https://jazz-lib-online-anwku.ondigitalocean.app/
                protocol: TCP
                port: 8080
                targetPort: 8080
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     
